# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HI Spatial
tagline: Tutorial Geospatial & WebGIS
email: hello@hispatial.com
description: >-
  HI Spatial adalah media yang membahas tutorial seputar geospatial, WebGIS, 
  pemetaan, dan teknologi spasial. Belajar Leaflet, Mapbox, QGIS, dan banyak lagi.
url: "https://hi-spatial.github.io"
baseurl: ""

# Open Graph / Social SEO
locale: id_ID
logo: "{{ '/assets/images/logo.png' | relative_url }}" # Add your logo image

# Webmaster Verifications (uncomment and add your codes)
# google_site_verification: YOUR_GOOGLE_VERIFICATION_CODE
# bing_site_verification: YOUR_BING_VERIFICATION_CODE
author:
  name: HI Spatial
  url: https://hispatial.com

# Social
twitter_username: hispatial
github_username: hispatial

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Pagination
paginate: 6
paginate_path: "/page/:num/"

# Allow future posts (for demo purposes)
future: true

# Collections for categories
collections:
  categories:
    output: true
    permalink: /category/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: HI Spatial
  - scope:
      path: ""
    values:
      layout: default

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Settings
twitter:
  card: summary_large_image

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
